#! /bin/bash
xsetwacom set "Wacom Intuos S 2 Pen stylus" Button 2 3
xsetwacom set "Wacom Intuos S 2 Pen stylus" Button 3 2

xsetwacom set "Wacom Intuos S 2 Pad pad" Button 3 "key ctrl z"
xsetwacom set "Wacom Intuos S 2 Pad pad" Button 1 "key ctrl y"

xsetwacom set "Wacom Intuos S 2 Pad pad" Button 8 "key e"
xsetwacom set "Wacom Intuos S 2 Pad pad" Button 9 "key p"

xsetwacom set "Wacom Intuos S 2 Pen stylus" Area 0 475 15200 9025
